# -*- coding: utf-8 -*-
"""homework3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vP7VOgBvV7ySHjnmmLA1JRUe9f_7mYSa
"""

import datetime
import pandas_datareader as pdr
import pandas as pd

api_key='7219b690b53b7b2a66c83339a10e570b926d12a3' # <your OWN API token aka key goes her


tickers = ['BP', 'TSLA', 'TWTR', 'MSFT']  # BP, TESLA, Twitter,  microsoft


start="2020-1-1"
end="2021-7-1"

df = pdr.tiingo.TiingoDailyReader(tickers, start=start, end=end, api_key=api_key)


all_data = df.read()
all_data

all_data.columns

import seaborn as sns
sns.set(rc={'figure.figsize':(22, 8)})
sns.lineplot(data=all_data, x='date', y='adjClose', hue='symbol');

# Import matplotlib
import matplotlib.pyplot as plt 

# Isolate the `Adj Close` values and transform the DataFrame
daily_close_px = all_data[['adjClose']].reset_index().pivot('date', 'symbol', 'adjClose')

# Calculate the daily percentage change for `daily_close_px`
daily_pct_change = daily_close_px.pct_change()

# Plot the distributions
daily_pct_change.hist(bins=50, sharex=True, figsize=(12,8))

# Show the resulting plot
plt.show()

"""# My observation:


1.   Overall:
*   The percentage change graph for each company is normally distributed
 
*  The majority of the time, these four leading big companies have steadily increasing or decreasing stock prices (likely following general market sentiment). 

*  All four companies are big-brand and well-known entities, and besides Telsa, much of their potential future earnings are 'priced in'. Although from the adjusted close price graph Telsa, Microsoft, and Twitter show generally increasing valuations.

---



2.   Individual Plots:


*   Tesla's graph is less centered around zero which shows how its stock price has greater variance up and down. This is to say, there are more dramatic than the other three, and there were more than 35 days where there was a negative percentage change, which indicates the stock price decreased during this period, but on the positive side having such price changes can help those with strategies relying on variable price.

*   Microsoft's graph is much more tightly centered around zero than the other three, meaning its stock price is relatively steadier than others, most of the time the changes close around 0%, and at zero for more than 50 days


*  For more than 60 days,  BP'stock price had negative growth, good days and bad days are roughly even, with swings of -0.2% to 0.2%. This likely correlates with oil price changes, general economic outlook, and political developments around oil-producing countries / OPEC price announcements.

*   For more than 50 days, Twitter'stock price had positive growth, there were a few days, and it had more than a 0.2% drop. It appears to stand between Microsoft and Telsa in terms of variability. 












"""

