# -*- coding: utf-8 -*-
"""homework3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vP7VOgBvV7ySHjnmmLA1JRUe9f_7mYSa
"""

import datetime
import pandas_datareader as pdr
import pandas as pd

api_key='7219b690b53b7b2a66c83339a10e570b926d12a3' # <your OWN API token aka key goes her


tickers = ['BP', 'TSLA', 'TWTR', 'MSFT']  # BP, TESLA, Twitter,  microsoft


start="2020-1-1"
end="2021-7-1"

df = pdr.tiingo.TiingoDailyReader(tickers, start=start, end=end, api_key=api_key)


all_data = df.read()
all_data

# Import matplotlib
import matplotlib.pyplot as plt 

# Isolate the `Adj Close` values and transform the DataFrame
daily_close_px = all_data[['adjClose']].reset_index().pivot('date', 'symbol', 'adjClose')

# Calculate the daily percentage change for `daily_close_px`
daily_pct_change = daily_close_px.pct_change()

# Plot the distributions
daily_pct_change.hist(bins=50, sharex=True, figsize=(12,8))

# Show the resulting plot
plt.show()

"""# My observation:


1.   Overall:
*   The percentage change graph for each company is normally distributed
 
*  The majority of time, these four leading big companies have steady stock prices, because the mode/median/mean of percentage change is same, positive and negative changes are small with 0.1%


---



2.   Individual:


*   Tesla's graph is less skewed than other three, it means its stock price had ups and downs, there are more changes than other three, and there were more than 35 days it had negative percentage change, which indicating the stock price decreased during this period, but on the positive side, there are larger blue area than negative side, it shows Tesla'stock had positive growth for most of time

*   Microsoft's graph is more skewed than other three, it means its stock price is relatively steadier than others, most of time the changes are closing 0.0%, these days are more than 50 days


*  For more than 60 days,  BP'stock price had negtive growth , good days and bad days are evenly close, there are few days, stock price went up 0.2% more, there are also few days, it had 0.19% drop

*   For more than 50 days , Twitter'stock price had positive growth, there were few days, it had more than 0.2% drop












"""

